const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    textYellow: '#FFF7C6',
    textGray: '#636362',
    background: '#20201F',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    theme: {
      yellow: '#FFF7C6',
      darkYellow: '#FDEEA4',
      moreDarkYellow: '#E8DB9E',
      white: '#EFEFEF',
      backgroundLightGreen: '#D0FFE6',
      backgroundDarkGreen: '#BCFADA',
      backgroundLightPink: '#FFE6FB',
      backgroundDarkPink: '#FFD1FF',
      backgroundLightYellow: '#FFF7C6',
      backgroundDarkYellow: '#FDEEA4',
      backgroundLightGray: '#282828',
      backgroundDarkGray: '#20201F',
      buttonOrange: '#EAB67D',
      buttonBlue: '#D0FFE6',
      buttonYellow: '#FFF7C6',
      buttonDarkYellow: '#FDEEA4',
      buttonPink: '#FFE6FB',
      buttonDarkPink: '#D385D6',
      buttonLightGreen: '#BCFADA',
      buttonGreen: '#7DCCA1',
      textLightGray: '#9C9C9C',
      textDarkGray: '#616161',
      textLightYellow: '#FFF7C6',
      textLightGreen: '#BCFADA',
      textLightPink: '#FFD1FF',
    },
  },
  dark: {
    text: '#fff',
    background: '#20201F',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
};
